### ISSUE TITLE
[Request] Support 'Scope by Storage' type view/queries

### ISSUE THREAD

**Issue by sjoeboo** [GoogleCloudPlatform/cloud-logging-data-source-plugin#16]
I am in an environment with heavy use of storage scoped logs (logs originate outside the project and are routed there via logging sinks), and it does not seem possible to query these logs with this plugin yet. 

Example:

in GCP Log Explorer UI, change scope to scope by storage.
create query (simple logname = projects/myproject/logs/myapp)
run query and verify. 
copy/paste query into Grafana GCL datasource
No Data found

**Comment by yvmori1** [comment]
We are in the same situation here.

**Comment by xiangshen-dk** [comment]
The scope feature has been added to rel 1.2.1. It implemented as dropdown menus with project/bucket/view. Let us know if you find any issue or have any feedback. Thanks!
