### ISSUE TITLE
Dashboard template variables are not interpolated in the `Log Panel` queries

### ISSUE THREAD

**Issue by tenequm** [GoogleCloudPlatform/cloud-logging-data-source-plugin#18]
I want to have the ability to run and show different logs on my Dashboard when I change the templated variable value.
It looks like now Log Panel doesn't want to interpolate variable values when using the Cloud Logging datasource.

![CleanShot 2023-02-24 at 19 54 48](https://user-images.githubusercontent.com/22403766/221253990-b116880e-f58d-45cd-974e-15af3eef4d23.png)

**Comment by dnck** [comment]
+1 @jeespers we are also in need of this feature asap. I'd hate to have to fork the repo just to get this feature.
