### ISSUE TITLE
Grafana Incident unable to display datasource query results

### ISSUE THREAD

**Issue by ramaro** [GoogleCloudPlatform/cloud-logging-data-source-plugin#23]
Hey,

When using this data source in Grafana Incident, I get an error `Data is missing a number field`, see screenshot below:

![Screenshot 2023-03-09 at 15 58 44](https://user-images.githubusercontent.com/544768/224081188-c5fa5496-956b-4909-9326-03d3b2d4a202.png)

I double checked the permissions are correct for this datasource as I can use it in a dashboard.

Using Grafana v9.4.3 (cloud) with latest plugin v1.1.1

If there's any other info I can provide, please let me know! Thanks

**Comment by xiangshen-dk** [comment]
Can you please try with the latest version of the plugin? Also, please check if the project id is set correctly.

**Comment by ramaro** [comment]
Hey @xiangshen-dk I just double checked this but unfortunately the problem still remains.

**Comment by GBBx** [comment]
Hi @ramaro , I think the root cause is that alerting is not currently supported (#28).

**Comment by xiangshen-dk** [comment]
After some digging, it appears alerting can't be implemented (see #28). Closing this one for now.
