### ISSUE TITLE
Feature Request: Support Grafana Alerting

### ISSUE THREAD

**Issue by melgl** [GoogleCloudPlatform/cloud-logging-data-source-plugin#28]
Hi folks! Are there any plans for this data source to support Grafana Alerting?
- [Grafana Alerting Data Source Compatibility](https://grafana.com/docs/grafana/latest/alerting/fundamentals/data-source-alerting/)

<img width="1041" alt="google_cloud_logging_data_source" src="https://user-images.githubusercontent.com/81323402/228085663-e634c68e-342e-4945-b6eb-7cf7ea4de26e.PNG">

**Comment by xiangshen-dk** [comment]
This feature will not be implemented. If needed, you can use log-based metrics + a monitoring data source for alerting. 
Updated the README at: https://github.com/GoogleCloudPlatform/cloud-logging-data-source-plugin#alerting

**Comment by Manuelraa** [comment]
> > This feature will not be implemented. If needed, you can use log-based metrics + a monitoring data source for alerting. Updated the README at: https://github.com/GoogleCloudPlatform/cloud-logging-data-source-plugin#alerting
> 
> Is it an technical limitation as written? If so please provide details. If not a contributor could create a PR (or fork).

Hi @xiangshen-dk could you please elaborate on the technical limitation?

**Comment by xiangshen-dk** [comment]
Based on [Grafana doc](https://grafana.com/docs/grafana/latest/alerting/fundamentals/alert-rules/queries-conditions/#data-source-queries), alerting queryies need to return numeric data, which is not supported by GCP logging queries. However, Loki does support [prometheus-compatible alerting rules](https://grafana.com/docs/loki/latest/alert/#alerting-rules). On GCP, similar capability is log-based metrics for alerting.
