### ISSUE TITLE
Support GCP ProjectID Variable

### ISSUE THREAD

**Issue by Tyrion85** [GoogleCloudPlatform/cloud-logging-data-source-plugin#32]
First of all, let me just say this project looks amazing! 

Is it possible to support a variable for GCP ProjectID, in Grafana `Logs` panel?

When I try to use a variable, its value is not taken in `Project ID` field:

<img width="979" alt="Screenshot 2023-04-03 at 14 14 24" src="https://user-images.githubusercontent.com/1699305/229506068-771559f9-9024-4b96-98e0-3d3f810b3de2.png">

**Comment by olekgo** [comment]
The lack of this feature is the only reason we aren't using this plugin in our environment. It would be awesome if it gets added!

**Comment by ClodoaldoHA** [comment]
+1

**Comment by xiangshen-dk** [comment]
It's been added in the release v1.3.0. Let us know if you found any issue.

Thanks all for the feedback!

**Comment by shibumi** [comment]
Hi,

Is there any way to "autoload" this variable? Right now, I have to statically predefine these project names and there is no way to make this a query variable.
