### ISSUE TITLE
GCP Audit logs displayed in the datasource are not JSON parseable

### ISSUE THREAD

**Issue by gsaxena-au** [GoogleCloudPlatform/cloud-logging-data-source-plugin#38]
Running a query like below in the Cloud Logging Plugin datasource in Grafana

```protoPayload.methodName=io.k8s.core.v1.pods.delete AND protoPayload.response.status.containerStatuses.state.terminated.reason="OOMKilled"```

shows the audit logs but they are not in JSON parse able.

**Comment by xiangshen-dk** [comment]
The new release addressed the issue. Let us know if you find any issue.

Thanks for the feedback!

**Comment by gsaxena-au** [comment]
Thanks @xiangshen-dk  for the fix!
